### ISSUE TITLE
How might the low power configuration interfere with gpio

### ISSUE THREAD

**Issue by fugata** [seamusdemora/PiFormulae#4]
Thanks for preparing the tutorial for programming the eeprom to a lower power mode!   I am new to pi and I have a question about how this config might affect gpio.

I came upon this mod

  https://www.hackster.io/shiva-siddharth/service-to-safe-shutdown-headless-raspberry-pi-boards-708269

that adds an on/off switch for the pi, using the gpio pins to triggle a python script.  I wonder if your eeprom change, specifically

   set WAKE_ON_GPIO=0 
   set POWER_OFF_ON_HALT=1

might render the on/off switch mode/script useless?

I have not yet gotten the parts and I am completely new to gpio; your help and comments are most welcome!  Thanks!

**Comment by seamusdemora** [comment]
Hello - sorry for the delayed response - I didn't see a notification - if I got one at all. Anyway...

## In answer to your question:
> I wonder if your eeprom change, specifically setting `WAKE_ON_GPIO=0` & `POWER_OFF_ON_HALT=1` might render the on/off switch mode/script useless?

*First, please note that his "recipe" does not apply to RPi 4. The `WAKE_ON_GPIO` & `POWER_OFF_ON_HALT` parameters apply ***ONLY*** to RPi 4. Here's a [similar approach that is claimed to work on RPi 4](https://howchoo.com/g/mwnlytk3zmm/how-to-add-a-power-button-to-your-raspberry-pi). That said...*

**_Answer:_** It might.  The WAKE_ON_GPIO` & `POWER_OFF_ON_HALT` parameters influence the PMIC (power management IC) operation during shutdown. The scheme you're interested in **may** depend on GPIO3 being *viable* in low-power shutdown mode. I don't know whether it is or not, but it's an interesting question! 

A brief search just now didn't reveal an answer to that question. However, if it ***does*** make a difference, there are **two work-arounds**, and one **recommended alternative** that should be enough to give you a green light to go ahead: 

### Work-around #1:
Do not change the values of `WAKE_ON_GPIO` & `POWER_OFF_ON_HALT` parameters, leave them at their defaults. This of course sacrifices the reduced power consumption in the low-power shutdown mode. But as you're connected to mains power (I assume), the cost of the additional electricity is very small.

### Work-around #2:
Instead of connecting one side of the switch to GPIO3, instead connect it to `GLOBAL_EN` (labeled on the PWA).

### Recommended:
Personally, I don't see the point of powering an RPi down with a push-button - it just seems silly. I say that because for me, it's not a big deal to open an SSH connection to my RPi, and enter a single command. My systems tend to stay "ON" most of the time, and I've almost always got an SSH session running to a laptop/desktop system. I **do** see some advantage in having a pushbutton to re-start a system as that avoids power-cycling by pulling & re-connecting the power cord. But no code is required for a push-button re-start! Here's how: 

Using a *momentary* N.O. push button switch, wire one side of the switch to GND, and wire the other side to the `GLOBAL_EN` node marked on the PWA. From your terminal, enter `sudo halt`, `sudo poweroff` or `sudo shutdown` to put the system in low-power shutdown mode. When you're ready to start your RPi, simply press the pushbutton once briefly.
